name             'effortless_generator'
maintainer       'Collin McNeese'
maintainer_email 'cmcneese@chef.io'
license          'Apache-2.0'
description      'Generates Chef Effortless Infrastructure repository with Chef CLI as part of Chef Workstation'
version          '0.1.0'
chef_version     '>= 14.0'
